Input
leszczynskidawid/precioz_app pull request #1
Opened 2022-06-08 14:56 UTC by leszczynskidawid

Cerate input with Miłosz

2022-06-08 19:49 UTC, baumanmilosz requested changes

2022-06-08 19:49 UTC, baumanmilosz commented on src/components/atoms/MyButton.js
> +import styled from "styled-components";
* nazwa `MyButton`? dlaczego to jest Twój button?
*  struktura folderów nie jest taka jak ustalalismy (`Atomic Design`) => np. components/atoms/Button(folder), a w nim Button.js i styles - warstwa styli powinna byc wyodrębniona do pliku ze stylami

2022-06-08 19:49 UTC, baumanmilosz commented on src/components/atoms/MyButton.js
> +export const Buttons = styled.button`
Buttons? - gdzie to uzywasz?

2022-06-08 19:49 UTC, baumanmilosz commented on src/components/atoms/MyButton.js
> +    <>
w jakim celu dodałeś `React Fragment`?

2022-06-08 19:49 UTC, baumanmilosz commented on .gitignore
> -# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
Ogólne uwagi
* nazwa PR'a `Input` - co to mówi osobie, która sprawdza Ci kod; co to mówi zespołowi, który musi wprowadzić zmiany w projekcie po x latach i patrzy na coś takiego? Nic. To ma być jasny komunikat co zrobileś w tym requescie (dodanie nowego feature'a, naprawa błędu, zmiana istniejącej już logiki etc.). Dodałeś bazowe komponenty UI do projektu - input, checkbox, button

2022-06-09 06:34 UTC, leszczynskidawid commented on src/components/atoms/MyButton.js
> +import styled from "styled-components";
struktura poprawiana, kazdy pojedynczy component zawiera sie w folderze w którym znajdują sie dwa pliki js z componentem i stylami . 
nazwa buttona zmieniona na Button

2022-06-09 06:34 UTC, leszczynskidawid commented on src/components/atoms/MyButton.js
> +export const Buttons = styled.button`
usunięto

2022-06-09 06:35 UTC, leszczynskidawid commented on src/components/atoms/MyButton.js
> +    <>
usunięto

2022-06-09 07:59 UTC, closed without merging